#!/usr/bin/env node
/**
 * Project and verify the single released TasteCheck inventory.
 *
 * release-facts.json is the authority for released skills, canonical commands,
 * the approved alias, gallery pages, and the release version. Derived JSON and
 * public inventory markers must be regenerated from it.
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const defaultRoot = new URL("../..", import.meta.url).pathname.replace(/\/$/, "");
const rootArgIndex = process.argv.indexOf("--root");
const root = resolve(rootArgIndex === -1 ? defaultRoot : process.argv[rootArgIndex + 1]);
const factsPath = join(root, "tools/release/release-facts.json");
const facts = JSON.parse(readFileSync(factsPath, "utf8"));
const write = process.argv.includes("--write");
const errors = [];

const generatedComment = "Generated by tools/release/project-facts.mjs from tools/release/release-facts.json; edit the source, not this file.";
const stable = (value) => {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort((left, right) => (left < right ? -1 : left > right ? 1 : 0)).map((key) => [key, stable(value[key])]));
  }
  return value;
};
const json = (value) => `${JSON.stringify(stable(value), null, 2)}\n`;
const sorted = (values) => [...values].sort();
const sameSet = (left, right) => JSON.stringify(sorted(left)) === JSON.stringify(sorted(right));
const rel = (path) => relative(root, path);
const numberWord = new Map([[1, "One"], [2, "Two"], [3, "Three"], [4, "Four"], [5, "Five"], [6, "Six"], [7, "Seven"], [8, "Eight"], [9, "Nine"], [10, "Ten"]]);
const inventoryLine = `Release inventory: v${facts.release_version} · ${facts.skills.length} skills · ${facts.commands.filter((c) => c.type === "canonical").length} canonical commands · ${facts.commands.filter((c) => c.type === "alias").length} alias · ${facts.commands.length} command files · ${facts.gallery.length} gallery systems.`;
const marker = `<!-- release-facts:v1:start -->\n${inventoryLine}\n<!-- release-facts:v1:end -->`;

function fail(message) { errors.push(message); }

function expectedManifest() {
  return {
    $comment: `${generatedComment} Landing marks concerns represented on the GitHub Pages integration surface.`,
    version: facts.release_version,
    skills: facts.skills,
  };
}

function expectedCommands() {
  const canonical = facts.commands.filter((entry) => entry.type === "canonical");
  const aliases = facts.commands.filter((entry) => entry.type === "alias");
  const targetCounts = new Map();
  for (const entry of facts.commands) targetCounts.set(entry.skill, (targetCounts.get(entry.skill) ?? 0) + 1);
  const duplicateTarget = [...targetCounts.entries()].find(([, count]) => count > 1) ?? [null, 0];
  return {
    schema_version: 1,
    description: `${generatedComment} ${canonical.length} canonical command entries, ${aliases.length} approved alias.`,
    commands: facts.commands,
    invariants: {
      total_command_files: facts.commands.length,
      canonical_commands: canonical.length,
      aliases: aliases.length,
      total_skills: facts.skills.length,
      approved_alias_files: aliases.map((entry) => entry.file),
      duplicate_target_skill: duplicateTarget[0],
      duplicate_target_count: duplicateTarget[1],
    },
  };
}

function compareJson(path, expected) {
  const actual = readFileSync(path, "utf8");
  if (!write && actual !== json(expected)) fail(`${rel(path)} is not projected byte-for-byte from release-facts.json`);
  if (write) writeFileSync(path, json(expected), "utf8");
}

function projectMarker(path) {
  const existing = readFileSync(path, "utf8");
  const start = existing.indexOf("<!-- release-facts:v1:start -->");
  const endMarker = "<!-- release-facts:v1:end -->";
  const end = existing.indexOf(endMarker);
  let projected = existing;
  if (start === -1 && end === -1) projected = `${marker}\n\n${existing}`;
  else if (start === -1 || end === -1 || end < start) fail(`${rel(path)} has a malformed release-facts marker`);
  else projected = `${existing.slice(0, start)}${marker}${existing.slice(end + endMarker.length)}`;
  if (write) writeFileSync(path, projected, "utf8");
  else if (projected !== existing) fail(`${rel(path)} release-facts marker is stale or missing`);
}

function validateSource() {
  if (facts.schema_version !== 1) fail("release-facts schema_version must be 1");
  const skillNames = facts.skills.map((skill) => skill.name);
  if (new Set(skillNames).size !== skillNames.length) fail("release-facts contains duplicate skill names");
  if (facts.skills.some((skill) => skill.landing !== true)) fail("every released skill must be landing:true in W2 inventory");
  const canonical = facts.commands.filter((entry) => entry.type === "canonical");
  const aliases = facts.commands.filter((entry) => entry.type === "alias");
  if (new Set(facts.commands.map((entry) => entry.file)).size !== facts.commands.length) fail("release-facts contains duplicate command files");
  if (new Set(facts.commands.map((entry) => entry.command)).size !== facts.commands.length) fail("release-facts contains duplicate command names");
  if (canonical.length !== facts.skills.length || !sameSet(canonical.map((entry) => entry.skill), skillNames)) fail("canonical command skills must equal released skills exactly");
  if (aliases.length !== 1 || aliases[0].skill !== "theming") fail("release-facts must contain exactly one approved theming alias");
  const diskSkills = readdirSync(join(root, "skills")).filter((name) => statSync(join(root, "skills", name)).isDirectory());
  if (!sameSet(diskSkills, skillNames)) fail("released skill set does not equal skills/ directories");
  const diskCommands = readdirSync(join(root, "commands")).filter((name) => name.endsWith(".md")).map((name) => `commands/${name}`);
  if (!sameSet(diskCommands, facts.commands.map((entry) => entry.file))) fail("command files do not equal release-facts command coverage");
  const diskGallery = readdirSync(join(root, "samples")).filter((name) => statSync(join(root, "samples", name)).isDirectory() && existsSync(join(root, "samples", name, "index.html")) && statSync(join(root, "samples", name, "index.html")).isFile());
  if (!sameSet(diskGallery, facts.gallery.map((entry) => entry.slug))) fail("gallery pages do not equal release-facts gallery coverage");
}

function validateSurfaces() {
  const packageJson = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
  if (packageJson.version !== facts.release_version) fail(`package.json version ${packageJson.version} does not equal release ${facts.release_version}`);
  compareJson(join(root, "skills.json"), expectedManifest());
  compareJson(join(root, "contracts/v1/commands.json"), expectedCommands());
  for (const file of ["README.md", "llms.txt", "index.html", "docs/LAUNCH.md", "docs/VERIFICATION.md", "samples/index.html"]) {
    projectMarker(join(root, file));
  }

  const manifest = JSON.parse(readFileSync(join(root, "skills.json"), "utf8"));
  const landing = readFileSync(join(root, "index.html"), "utf8");
  const sampleIndex = readFileSync(join(root, "samples/index.html"), "utf8");
  const landingSkills = [...new Set([...landing.matchAll(/data-skill="([^"]+)"/g)].map((match) => match[1]))];
  const galleryCards = [...sampleIndex.matchAll(/<a class="card [^"]+" href="([^/]+)\/index\.html">/g)].map((match) => match[1]);
  if (!sameSet(landingSkills, manifest.skills.map((skill) => skill.name))) fail("landing data-skill set does not equal released skills");
  if (!sameSet(galleryCards, facts.gallery.map((entry) => entry.slug))) fail("gallery card set does not equal release-facts gallery");
  if (!landing.includes(`skillCount:${facts.skills.length}`)) fail("landing browser contract skillCount is stale");
  if (!landing.includes(`softwareVersion": "${facts.release_version}"`)) fail("landing softwareVersion is stale");
  if (!sampleIndex.includes(`One page. ${numberWord.get(facts.gallery.length) ?? facts.gallery.length} committed design systems.`)) fail("gallery heading is stale");
}

validateSource();
validateSurfaces();
if (errors.length) {
  console.error(`release inventory projection failed (${errors.length})`);
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}
console.log(`${write ? "projected" : "verified"} release inventory: v${facts.release_version}; ${facts.skills.length} skills; ${facts.commands.filter((c) => c.type === "canonical").length} canonical commands; ${facts.commands.filter((c) => c.type === "alias").length} alias; ${facts.gallery.length} gallery systems`);
